export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  BRANCH_ADMIN = 'BRANCH_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  PHARMACIST = 'PHARMACIST',
  CASHIER = 'CASHIER',
  HR = 'HR',
  WAREHOUSE_STAFF = 'WAREHOUSE_STAFF',
  FINANCE_STAFF = 'FINANCE_STAFF',
  RECEPTIONIST = 'RECEPTIONIST',
}
